### ISSUE TITLE
Todo 22.11.02

### ISSUE THREAD

**Issue by Leejin-Yang** [Leejin-Yang/Leejin-Yang#10]
- [x] 프리코스 2주차 요구 사항 분석
- [x] 프리코스 2주차 eslint, prettier 설정
- [x] 알고리즘 강의 섹션 1

**Comment by Leejin-Yang** [comment]
https://github.com/Leejin-Yang/javascript-baseball/commits/Leejin-Yang
